server:
  port: 8888
  
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/Armando122/Desarrollo-Web-Backend-Proyecto.git
          search-paths: config-data/api

          default-label: "main"
          
  security:
    user:
      name: root
      password: adminadmin
